config/routes.rb
Rails.application.routes.draw do
  root 'services#index'
  resources :categories
  resources :workers
  resources :services
  resources :orders do
    get :export, on: :collection, defaults: { format: :xlsx }
  end
end

app/models/service.rb
class Service < ApplicationRecord
  include Discard::Model

  validates :name, presence: true, length: { minimum: 3 }

  belongs_to :category

  scope :order_by_name, ->(direction) { order(name: direction) }
  scope :order_by_category, ->(direction) { order("categories.name #{direction}") }

  scope :filter_by_name, ->(name) { where("services.name like ?", "%#{name}%") }
  scope :filter_by_category, ->(name) { references(:categories).where("categories.name like ?", "%#{name}%") }
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: %i[ show edit update destroy ]

  # GET /services or /services.json
  def index
    @services = Service.includes(:category).kept
    @services = @services.filter_by_name(params[:filter_by_name]) if params[:filter_by_name].present?
    @services = @services.filter_by_category(params[:filter_by_category]) if params[:filter_by_category].present?
    @services = @services.order_by_name(params[:order_by_name]) if params[:order_by_name].present?
    @services = @services.order_by_category(params[:order_by_category]) if params[:order_by_category].present?
  end

  # GET /services/1 or /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services or /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to service_url(@service), notice: "Услуна была успешно создана." }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1 or /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to service_url(@service), notice: "Услуга была успешно обновлена." }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1 or /services/1.json
  def destroy
    @service.discard

    respond_to do |format|
      format.html { redirect_to services_url, notice: "Услуга была успешно удалена." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def service_params
      params.require(:service).permit(:name, :category_id)
    end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.slim
div
  = form_with(model: @service, class: 'space-y-4') do |form|
    - if @service.errors.any?
      div style="color: red"
        ul
          - @service.errors.each do |error|
            li = error.full_message
    div
      = form.label :name, 'Название'
      = form.text_field :name
    div
      = form.label :category_id, 'Категория'
      = form.collection_select :category_id, Category.order(:name), :id, :name

    div
      = form.submit 'Сохранить'

app/views/services/edit.html.slim
div

  h1 Редактировать сервис

  == render "form", service: @service

  ul
    li= link_to "Показать сервис", @service
    li= link_to "К списку сервисов", services_path

app/views/services/index.html.slim
p style="color: green" = notice

h1 Услуги

div= link_to "Добавить услугу", new_service_path

= form_with url: services_path, method: :get do |f|
  = f.text_field :filter_by_name, value: params[:filter_by_name], placeholder: 'Название'
  = f.text_field :filter_by_category, value: params[:filter_by_category], placeholder: 'Категория'
  = f.submit 'Поиск'
  = link_to 'Сбросить фильтр', services_path

table
  thead
      th
        div= link_order 'Название', :services_path, :order_by_name
      th
        div= link_order 'Категория', :services_path, :order_by_category
      th
        div Действие
  tbody
    - @services.each do |service|
      tr
        td= link_to service.name, service
        td
          - if service.category.discarded?
            = service.category.name
          - else
            = link_to service.category.name, category_path(service.category)
        td= link_to 'Редактировать', edit_service_path(service)
        td= button_to 'Удалить', service, method: :delete

app/views/services/new.html.slim
div
  h1 Создать новую услугу

  == render "form", service: @service

  div
    = link_to "К списку сервисов", services_path

app/views/services/show.html.slim
p style="color: green" = notice

div
  h1= @service.name
  ul
    li= link_to "Назад", services_path
    li= link_to "Редактировать", edit_service_path(@service)
    = button_to "Удалить", @service, method: :delete