config/routes.rb
Rails.application.routes.draw do
  root 'services#index'
  resources :categories
  resources :workers
  resources :services
  resources :orders do
    get :export, on: :collection, defaults: { format: :xlsx }
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items, dependent: :destroy

  accepts_nested_attributes_for :order_items, allow_destroy: true

  validates :customer_name, presence: true

  scope :order_by_date, ->(direction) { order("orders.created_at #{direction}") }
  scope :order_by_customer_name, ->(direction) { order("orders.customer_name #{direction}") }
  scope :order_by_category, ->(direction) { order("categories.name #{direction}") }
  scope :order_by_service, ->(direction) { order("services.name #{direction}") }
  scope :order_by_worker, ->(direction) { order("workers.name #{direction}") }

  scope :filter_by_date_from, -> (date) { where("orders.created_at >= ?", date) }
  scope :filter_by_date_to, -> (date) { where("orders.created_at <= ?", date) }
  scope :filter_by_customer_name, -> (name) { where('customer_name like ?', "%#{name}%") }
  scope :filter_by_category, -> (name) { references(order_items: [{service: :category}]).where('categories.name like ?', "%#{name}%") }
  scope :filter_by_service, -> (name) { references(order_items: :service).where('services.name like ?', "%#{name}%") }
  scope :filter_by_worker, -> (name) { references(order_items: :worker).where('workers.name like ?', "%#{name}%") }
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[ show edit update destroy ]

  # GET /orders or /orders.json
  def index
    set_orders
  end

  # GET /orders/1 or /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
    @order.order_items.build
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders or /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to order_url(@order), notice: "Заказ был успешно создан." }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to order_url(@order), notice: "Заказ был успешно обновлен." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Заказ был успешно удален." }
      format.json { head :no_content }
    end
  end

  def export
    set_orders

    respond_to do |format|
      format.xlsx {
        response.headers['Content-Disposition'] = "attachment; filename=orders_#{Time.now.strftime('%Y-%m-%d %H_%M_%S')}.xlsx"
      }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.includes(order_items: [{service: :category}, :worker]).find(params[:id])
    end

    def set_orders
      @orders = Order.includes(order_items: [:worker, {service: :category}])

      @orders = @orders.order_by_date(params[:order_by_date]) if params[:order_by_date].present?
      @orders = @orders.order_by_customer_name(params[:order_by_customer_name]) if params[:order_by_customer_name].present?
      @orders = @orders.order_by_category(params[:order_by_category]) if params[:order_by_category].present?
      @orders = @orders.order_by_service(params[:order_by_service]) if params[:order_by_service].present?
      @orders = @orders.order_by_worker(params[:order_by_worker]) if params[:order_by_worker].present?

      @orders = @orders.filter_by_date_from(params[:filter_by_date_from]) if params[:filter_by_date_from].present?
      @orders = @orders.filter_by_date_to(params[:filter_by_date_to]) if params[:filter_by_date_to].present?
      @orders = @orders.filter_by_customer_name(params[:filter_by_customer_name]) if params[:filter_by_customer_name].present?
      @orders = @orders.filter_by_category(params[:filter_by_category]) if params[:filter_by_category].present?
      @orders = @orders.filter_by_service(params[:filter_by_service]) if params[:filter_by_service].present?
      @orders = @orders.filter_by_worker(params[:filter_by_worker]) if params[:filter_by_worker].present?
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:customer_name, order_items_attributes: [:id, :service_id, :worker_id, :_destroy])
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.slim
= form_with(model: @order) do |f|
  - if @order.errors.any?
    div style="color: red"
      ul
        - @order.errors.each do |error|
          li = error.full_message

  div
    = f.label :customer_name, 'Имя покупателя', style: "display: block"
    = f.text_field :customer_name

  h2 Услуги

  div
    = link_to_add_nested(f, :order_items, '#order-items', link_text: 'Добавить услугу')

  #order-items
    = f.fields_for :order_items do |ff|
      = render 'order_item_fields', form: ff
        

  div
    = f.submit 'Сохранить'

app/views/orders/_order.html.slim
div id="#{dom_id order}"
  p
    strong Customer name:
    =< order.customer_name
  p
    strong Worker:
    =< order.worker_id

app/views/orders/_order_item_fields.html.slim
div
	= form.collection_select :service_id, Service.kept.order(:name), :id, :name
	= form.collection_select :worker_id, Worker.kept.order(:name), :id, :name
	= link_to_remove_nested(form)

app/views/orders/edit.html.slim
h1 Редактировать заказ

== render "form", order: @order

br

ul
  li= link_to "Показать заказ", @order
  li= link_to "К списку заказов", orders_path

app/views/orders/index.html.slim
p style="color: green" = notice

h1 Заказы

= link_to "Добавить заказ", new_order_path

= button_to 'Экспортировать в Excel', export_orders_path, method: :get, params: params.permit!, form: {data: {turbo: false}}

= form_with url: orders_path, method: :get do |f|
  div
    span От
    = f.text_field :filter_by_date_from, type: :date, value: params[:filter_by_date_from]
  div
    span До
    = f.text_field :filter_by_date_to, type: :date, value: params[:filter_by_date_to]
  = f.text_field :filter_by_customer_name, value: params[:filter_by_customer_name], placeholder: 'Имя покупателя'
  = f.text_field :filter_by_category, value: params[:filter_by_category], placeholder: 'Название категории'
  = f.text_field :filter_by_service, value: params[:filter_by_service], placeholder: 'Название услуги'
  = f.text_field :filter_by_worker, value: params[:filter_by_worker], placeholder: 'Имя исполнителя'
  = f.submit 'Поиск'
  = link_to 'Сбросить фильтр', orders_path

table
  thead
    th
      div= link_order 'Дата', :orders_path, :order_by_date
    th
      div= link_order 'Заказчик', :orders_path, :order_by_customer_name
    th
      div= link_order 'Категория', :orders_path, :order_by_category
    th
      div= link_order 'Услуга', :orders_path, :order_by_service
    th
      div= link_order 'Исполнитель', :orders_path, :order_by_worker
    th
      div Действия
  tbody
    - @orders.each do |order|
      tr
        td= link_to l(order.created_at), order
        td= order.customer_name
        td
          ul
            - order.order_items.each do |order_item|
              - if order_item.service.category.discarded?
                li= order_item.service.category.name
              - else
                li= link_to order_item.service.category.name, order_item.service.category
        td
          ul
            - order.order_items.each do |order_item|
              - if order_item.service.discarded?
                li= order_item.service.name
              - else
                li= link_to order_item.service.name, order_item.service
        td
          ul
            - order.order_items.each do |order_item|
              - if order_item.worker.discarded?
                li= order_item.worker.name
              - else
                li= link_to order_item.worker.name, order_item.worker
        td
          = link_to 'Редактировать', edit_order_path(order)
          = button_to 'Удалить', order, method: :delete

app/views/orders/new.html.slim
h1 Новый заказ

== render "form", order: @order

= link_to "Назад", orders_path

app/views/orders/show.html.slim
p style="color: green" = notice

h1 Заказ для #{@order.customer_name} от #{l @order.created_at}

h2 Услуги

table
  thead
    th Категория
    th Услуга
    th Исполнитель
  tbody
    - @order.order_items.each do |order_item|
      tr
        td= link_to order_item.service.category.name, order_item.service.category
        td= link_to order_item.service.name, order_item.service
        td= link_to order_item.worker.name, order_item.worker

ul
  li= link_to "Редактировать", edit_order_path(@order)
  li= link_to "К списку заказов", orders_path
  = button_to "Удалить", @order, method: :delete