config/routes.rb
Rails.application.routes.draw do
  root 'services#index'
  resources :categories
  resources :workers
  resources :services
  resources :orders do
    get :export, on: :collection, defaults: { format: :xlsx }
  end
end

app/models/worker.rb
class Worker < ApplicationRecord
  include Discard::Model

  validates :name, presence: true, length: { minimum: 2 }

  scope :filter_by_name, ->(name) { where('workers.name like ?', "%#{name}%") }
  scope :order_by_name, ->(direction) { order("workers.name #{direction}") }
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  before_action :set_worker, only: %i[ show edit update destroy ]

  # GET /workers or /workers.json
  def index
    @workers = Worker.kept
    @workers = @workers.order_by_name(params[:order_by_name]) if params[:order_by_name].present?
    @workers = @workers.filter_by_name(params[:filter_by_name]) if params[:filter_by_name].present?
  end

  # GET /workers/1 or /workers/1.json
  def show
  end

  # GET /workers/new
  def new
    @worker = Worker.new
  end

  # GET /workers/1/edit
  def edit
  end

  # POST /workers or /workers.json
  def create
    @worker = Worker.new(worker_params)

    respond_to do |format|
      if @worker.save
        format.html { redirect_to worker_url(@worker), notice: "Рабочий был успешно создан." }
        format.json { render :show, status: :created, location: @worker }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workers/1 or /workers/1.json
  def update
    respond_to do |format|
      if @worker.update(worker_params)
        format.html { redirect_to worker_url(@worker), notice: "Рабочий был успешно обновлен." }
        format.json { render :show, status: :ok, location: @worker }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workers/1 or /workers/1.json
  def destroy
    @worker.discard

    respond_to do |format|
      format.html { redirect_to workers_url, notice: "Рабочий был успешно удален." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_worker
      @worker = Worker.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def worker_params
      params.require(:worker).permit(:name)
    end
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/workers/_form.html.slim
= form_with(model: @worker) do |form|
  - if @worker.errors.any?
    div style="color: red"
      ul
        - @worker.errors.each do |error|
          li = error.full_message

  div
    = form.label :name, 'Имя', style: "display: block"
    = form.text_field :name

  div
    = form.submit 'Сохранить'

app/views/workers/edit.html.slim
h1 Редактировать рабочего

== render "form", worker: @worker

ul
  li= link_to "Показать рабочего", @worker
  li= link_to "К списку рабочих", workers_path

app/views/workers/index.html.slim
p style="color: green" = notice

h1 Рабочие

= link_to "Добавить рабочего", new_worker_path

= form_with url: workers_path, method: :get do |f|
  = f.text_field :filter_by_name, value: params[:filter_by_name]
  = f.submit 'Поиск'
  = link_to 'Сбросить фильтр', workers_path
table
  thead
    th
      div= link_order 'Имя', :workers_path, :order_by_name
    th
      div Действие
  tbody
    - @workers.each do |worker|
      tr
        td= link_to worker.name, worker
        td= link_to 'Редактировать', edit_worker_path(worker)
        td= button_to 'Удалить', worker, method: :delete

app/views/workers/new.html.slim
h1 Добавить рабочего

== render "form", worker: @worker

br

div
  = link_to "Назад", workers_path

app/views/workers/show.html.slim
p style="color: green" = notice

h1= @worker.name

ul
  li= link_to "Редактировать", edit_worker_path(@worker)
  li= link_to "К списку рабочих", workers_path
  = button_to "Удалить", @worker, method: :delete